<?php
/******************************************************
 * @package Ves Megamenu module for Magento 1.4.x.x and Magento 1.7.x.x
 * @version 1.0.0.1
 * @author http://landofcoder.com
 * @copyright	Copyright (C) December 2010 LandOfCoder.com <@emai:landofcoder@gmail.com>.All rights reserved.
 * @license		GNU General Public License version 2
*******************************************************/
?>
<div style="clear:both"></div>
<div class="menunongroup">
	<div class="main">
		<div class="vesmegamenu-top menu-top vesclear">
			<div id="vesmegamenu<?php echo $config['topCategory']; ?>" class="ddsmoothmenu">
				<ul id="vesmegamenu" class="level0">
					<?php echo $menuHtml; ?>
				</ul>		
			</div>
		</div>
		<?php if( $responsive ): ?>
			<div class="ves-responmenu vesclear" id="vesresponmenu">
				<h2 class="nav-button"><a href="#"><span><?php echo ("Menu");?></span></a></h2>
				<div class="responmenu-wrapper vesclear" ><?php echo $responsive;?></div>
			</div>
		<?php endif; ?>
			
	</div>
</div>
<?php echo isset($content)?$content:""; ?>